name: Destroy infrastructure
on:
    workflow_dispatch:
jobs:
    destroy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: hashicorp/setup-terraform@v3
              with: { terraform_version: "~1.10" }
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-actions-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            - run: terraform init
              working-directory: infra
            - run: terraform destroy -auto-approve
                    -var="app_name=infra_proj"
                    -var="aws_region=us-east-1"
              working-directory: infra